[SERVICE]
    flush        5
    daemon       Off
    log_level    info
    parsers_file parsers.conf

[INPUT]
    name              tail
    path              /mnt/security-logs/suricata/eve.json
    tag               suricata
    parser            json
    db                /var/lib/fluent-bit/suricata.db
    read_from_head    Off

[INPUT]
    name              tail
    path              /mnt/security-logs/zeek/current/conn.log
    tag               zeek.conn
    db                /var/lib/fluent-bit/zeek-conn.db
    read_from_head    Off

[INPUT]
    name              tail
    path              /mnt/security-logs/zeek/current/dns.log
    tag               zeek.dns
    db                /var/lib/fluent-bit/zeek-dns.db
    read_from_head    Off

[OUTPUT]
    name              es
    match             *
    host              100.102.95.78
    port              9200
    index             security-logs
    http_user         elastic
    http_passwd       KPJ*AYQ7sZFpgVvr!p
    tls               Off
    suppress_type_name On
